Adding unit tests for com.taobao.arthas.core
Diffblue-benchmarks/Alibaba-arthas pull request #5
Opened 2019-08-19 14:25 UTC by EdgarScott

I've analysed your codebase and noticed that `com.taobao.arthas.core` is not fully tested.
I've written some tests for the methods in this class with the help of [Diffblue Cover](https://www.diffblue.com/opensource).

Hopefully, these tests will help you detect any regressions caused by future code changes. If you would find it useful to have additional tests written for this repository, I would be more than happy to look at other classes that you consider important.

2019-08-20 08:25 UTC, paulkennethkent requested changes

2019-08-20 08:25 UTC, paulkennethkent commented on core/pom.xml
>      </dependencies>
Only add dependencies as required, I can't see powermock, deeptest-utils being needed for these tests?

2019-08-20 08:25 UTC, paulkennethkent commented on core/src/test/java/com/taobao/arthas/core/util/ObjectUtilsTest.java
> +  }
It's fine to submit these test but definitely worth creating an enhancement request on these

2019-08-22 10:03 UTC, closed without merging

2019-08-22 10:04 UTC, EdgarScott commented
External PR submitted https://github.com/alibaba/arthas/pull/823